{% set name = "TreeTool" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/porteratzo/TreeTool/tree/setup

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  license: MIT
  license_family: MIT
  summary: Tool to extract tree trunks and diameter at breast height from TLS forest point clouds